- hosts: wolverine
  become: true
  roles:
    - role: '../roles/tftp-server'
      image_url: https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2024-07-04/2024-07-04-raspios-bookworm-armhf-lite.img.xz
      nfs_folder_name: 2c-cf-67-66-e8-3b
      hostname: deadpool
