- name: Execute the pre-condistions for the installation
  ansible.builtin.import_tasks: task/00.pre.install.yaml
- name: Install all nessacary packages
  ansible.builtin.include_tasks: task/01.install.dependencies.yaml
- name:  
  ansible.builtin.import_tasks: task/02.install.java.yaml
- name:  
  ansible.builtin.import_tasks: task/03.create.user.yaml
- name:  
  ansible.builtin.import_tasks: task/04.install.openhab.yaml
- name:  
  ansible.builtin.import_tasks: task/20.create.mountpoints.yaml

