image.url: https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2024-07-04/2024-07-04-raspios-bookworm-armhf-lite.img.xz
#image.file: 2024-07-04-raspios-bookworm-armhf-lite.img
image.file: = {{ image.url.split('_') | last | replace('.xz','') }}
image.destination: /home/{{ansible_user}}/images
nfs.folder.name: 2c-cf-67-66-e8-3b
mount.rootfs.location: /mnt/tmp/root/
mount.bootfs.location: /mnt/tmp/boot/