- name: "Check if openjdk-17-jre is installed and install it when missing"
  apt: 
    name: openjdk-17-jre 
    state: present 
    update_cache: true
    when: "'openjdk-17-jre' not in ansible_facts.packages"
- name: Install pexpect
  apt:
    update_cache: yes
    name:
      - python3-pexpect