- name: Create temporary boot directory
  ansible.builtin.file:
    path: "{{ mount_rootfs_location }}"
    state: directory
- name: Create temporary rootfs directory
  ansible.builtin.file:
    path: "{{mount_bootfs_location}}"
    state: directory
- name: Create download directory for the image we want to download. 
  ansible.builtin.file:
    path: "{{image_destination}}"
    state: directory