- name: Transmit the rootfs to the NAS share
  ansible.builtin.command: rsync -xa --progress {{mount.rootfs.location}} /mnt/nfsshare/rootfs/{{nfs.folder.name}}
- name: Transmit the boot files to the NAS share
  ansible.builtin.command: rsync -xa --progress {{mount.bootfs.location}}/mnt/nfsshare/tftp/{{nfs.folder.name}}