- name: delete the partuuid entries in the fstab
  ansible.builtin.lineinfile:
    path: '/mnt/nfsshare/rootfs/{{nfs_folder_name}}/etc/fstab'
    regexp: 'PARTUUID'
    line: '192.168.178.30:/volume1/tftp/{{nfs_folder_name}} /boot nfs defaults,vers=3,proto=tcp 0 0'
- name: Copy boot files to rootfs
  copy:
    remote_src: yes
    src: /mnt/nfsshare/tftp/{{nfs_folder_name}}/
    dest: /mnt/nfsshare/rootfs/{{nfs_folder_name}}/boot
- name: Ersetze die erste Zeile in der Datei mit einem neuen Text
  lineinfile:
        path: '/mnt/nfsshare/tftp/{{nfs_folder_name}}/cmdline.txt'
        regexp: '^.*'  # Regex, die die gesamte erste Zeile erfasst
        line: 'console=serial0,115200 console=tty1 root=/dev/nfs nfsroot=192.168.178.30:/volume1/rootfs/{{nfs_folder_name}},vers=3 rw ip=dhcp rootwait elevator=deadline debug nfsrootdebug systemd.run=/opt/firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target'
        firstmatch: true  # Nur das erste Auftreten ersetzen
- name: Copy firstrun script to /mnt/nfsshare/rootfs/{{nfs_folder_name}}/opt/"
  copy:
    dest: "/mnt/nfsshare/rootfs/{{nfs_folder_name}}/opt/"
    src: "/mnt/nfsshare/tftp/common/firstrun.sh"
    mode: '0777'
    remote_src: yes
- name: Replace hostname in firstrun script with {{ hostname }}
  replace:
    path: "/mnt/nfsshare/rootfs/{{nfs_folder_name}}/opt/firstrun.sh"
    regexp: 'netbootmaker'
    replace: "{{ hostname }}"
